apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-models-pvc
  namespace: triton
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp2
---
apiVersion: batch/v1
kind: Job
metadata:
  name: llm-model-downloader
  namespace: triton
spec:
  template:
    spec:
      nodeSelector:
        workload: llm-inference
        gpu: "true"
      
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      
      restartPolicy: OnFailure
      containers:
      - name: model-downloader
        image: python:3.10-slim
        command:
        - bash
        - -c
        - |
          pip install huggingface-hub
          
          export HF_HOME=/models/huggingface
          mkdir -p $HF_HOME
          
          # Download Llama 3 8B GPTQ (compatible with T4)
          echo "Downloading Llama 3 8B GPTQ..."
          python3 -c "
          from huggingface_hub import snapshot_download
          snapshot_download(
              repo_id='TheBloke/Llama-2-7B-Chat-GPTQ',
              local_dir='/models/llama2-7b-gptq',
              local_dir_use_symlinks=False
          )
          "
          
          echo "Model download complete!"
          ls -lh /models/
          
        volumeMounts:
        - name: models
          mountPath: /models
      volumes:
      - name: models
        persistentVolumeClaim:
          claimName: llm-models-pvc