apiVersion: v1
kind: Service
metadata:
  name: vllm-service
  namespace: triton
spec:
  selector:
    app: vllm
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm
  namespace: triton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm
  template:
    metadata:
      labels:
        app: vllm
    spec:
      # Schedule on GPU nodes
      nodeSelector:
        workload: llm-inference
        gpu: "true"
      
      # Tolerate GPU taints
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      
      containers:
      - name: vllm
        image: vllm/vllm-openai:latest
        command:
        - python3
        - -m
        - vllm.entrypoints.openai.api_server
        args:
        - --model=/models/llama3-8b-awq
        - --tensor-parallel-size=1
        - --gpu-memory-utilization=0.9
        - --max-model-len=4096
        - --host=0.0.0.0
        - --port=8000
        - --served-model-name=llama3-8b
        - --quantization=awq
        
        ports:
        - containerPort: 8000
          name: http
        
        resources:
          requests:
            nvidia.com/gpu: 1
            memory: "12Gi"
            cpu: "4"
          limits:
            nvidia.com/gpu: 1
            memory: "14Gi"
            cpu: "4"
        
        volumeMounts:
        - name: models
          mountPath: /models
          readOnly: true
        
        env:
        - name: HF_HOME
          value: /models/huggingface
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
        
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 300  # Model loading takes time
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 300
          periodSeconds: 10
          timeoutSeconds: 5
      
      volumes:
      - name: models
        persistentVolumeClaim:
          claimName: llm-models-pvc
      
      # Increase startup time for model loading
      terminationGracePeriodSeconds: 60