apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ab-config
  namespace: triton
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        upstream triton_backend {
            server triton-service:8000;
        }
        
        log_format ab_test '$remote_addr - $backend - $request_time - $status';
        
        server {
            listen 8080;
            access_log /var/log/nginx/ab_test.log ab_test;
            
            location / {
                # Add custom header to track variant
                set $variant "xgboost-control";
                
                # Simple random assignment based on IP
                if ($remote_addr ~* "[02468]$") {
                    set $variant "xgboost-control";
                }
                if ($remote_addr ~* "[13579]$") {
                    set $variant "catboost-variant";
                }
                
                proxy_pass http://triton_backend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Model-Variant $variant;
                
                add_header X-Model-Variant $variant always;
                add_header X-AB-Test "active" always;
            }
            
            location /health {
                access_log off;
                return 200 "healthy\n";
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ab-traffic-router
  namespace: triton
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ab-router
  template:
    metadata:
      labels:
        app: ab-router
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-ab-config
---
apiVersion: v1
kind: Service
metadata:
  name: ab-traffic-router
  namespace: triton
spec:
  selector:
    app: ab-router
  ports:
  - name: http
    port: 80
    targetPort: 8080