apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton-anomaly-detector
  namespace: ml-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: triton-anomaly-detector
  template:
    metadata:
      labels:
        app: triton-anomaly-detector
    spec:
      initContainers:
      - name: model-downloader
        image: amazon/aws-cli:latest
        command:
        - sh
        - -c
        - |
          echo "Downloading models from S3..."
          aws s3 sync s3://triton-models-71544/models/ /models/ --region us-east-1
          echo "Download complete. Files:"
          ls -R /models/
        env:
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
        - name: model-repository
          mountPath: /models
      containers:
      - name: triton
        image: nvcr.io/nvidia/tritonserver:23.10-py3
        command:
        - tritonserver
        args:
        - --model-repository=/models
        - --log-verbose=1
        - --strict-model-config=false
        - --exit-on-error=false
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 8001
          name: grpc
        - containerPort: 8002
          name: metrics
        volumeMounts:
        - name: model-repository
          mountPath: /models
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /v2/health/live
            port: 8000
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /v2/health/ready
            port: 8000
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
      volumes:
      - name: model-repository
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: triton-anomaly-detector
  namespace: ml-inference
spec:
  type: LoadBalancer
  selector:
    app: triton-anomaly-detector
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  - name: grpc
    port: 8001
    targetPort: 8001
  - name: metrics
    port: 8002
    targetPort: 8002