apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton-server
  namespace: triton
  labels:
    app: triton-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: triton-server
  template:
    metadata:
      labels:
        app: triton-server
    spec:
      serviceAccountName: triton-sa
      initContainers:
      - name: model-downloader
        image: amazon/aws-cli:latest
        command:
        - sh
        - -c
        - |
          echo "Downloading models from S3..."
          aws s3 sync s3://triton-models-2403/models/ /models/ --region us-east-1
          echo "Models downloaded successfully"
          ls -la /models/
        volumeMounts:
        - name: model-storage
          mountPath: /models
        env:
        - name: AWS_REGION
          value: "us-east-1"
      containers:
      - name: triton
        image: nvcr.io/nvidia/tritonserver:23.10-py3
        command:
        - tritonserver
        args:
        - --model-repository=/models
        - --log-verbose=1
        - --http-port=8000
        - --grpc-port=8001
        - --metrics-port=8002
        - --exit-on-error=false
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 8001
          name: grpc
        - containerPort: 8002
          name: metrics
        volumeMounts:
        - name: model-storage
          mountPath: /models
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /v2/health/live
            port: 8000
          initialDelaySeconds: 90
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /v2/health/ready
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
      volumes:
      - name: model-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: triton-service
  namespace: triton
  labels:
    app: triton-server
spec:
  type: LoadBalancer
  selector:
    app: triton-server
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: grpc
  - port: 8002
    targetPort: 8002
    protocol: TCP
    name: metrics