# Isolation Forest Configuration
isolation_forest:
  n_estimators: 100
  contamination: 0.1
  max_samples: "auto"
  random_state: 42

# XGBoost Configuration
xgboost:
  objective: "binary:logistic"
  max_depth: 6
  learning_rate: 0.1
  n_estimators: 100
  subsample: 0.8
  colsample_bytree: 0.8
  random_state: 42
  eval_metric: "auc"

# CatBoost Configuration
catboost:
  iterations: 100
  learning_rate: 0.1
  depth: 6
  loss_function: "Logloss"
  random_seed: 42
  verbose: False

# Model Evaluation
evaluation:
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1_score"
    - "roc_auc"
  threshold: 0.5