apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: mlflow
type: Opaque
stringData:
  POSTGRES_USER: mlflow
  POSTGRES_PASSWORD: ChangeMeInProduction123!
  POSTGRES_DB: mlflow_db
  DATABASE_URL: postgresql://mlflow:ChangeMeInProduction123!@postgres-service:5432/mlflow_db